BEGIN;

-- Users
CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(150) UNIQUE,
  password TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  is_authorized BOOLEAN DEFAULT FALSE,
  role VARCHAR(20),
  confidence_score INTEGER DEFAULT 0,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

-- Checkpoints
CREATE TABLE IF NOT EXISTS checkpoints (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(150),
  city VARCHAR(100),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  current_status VARCHAR(50),
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

-- Reports
CREATE TABLE IF NOT EXISTS reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  title VARCHAR(200),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  category VARCHAR(50),
  description TEXT,
  status VARCHAR(20),
  confidence_score INTEGER,
  duplicate_of INTEGER,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  CONSTRAINT fk_reports_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_reports_duplicate
    FOREIGN KEY (duplicate_of)
    REFERENCES reports(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

-- Incidents
CREATE TABLE IF NOT EXISTS incidents (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200),
  category VARCHAR(50),
  description TEXT,
  severity VARCHAR(20),
  status VARCHAR(20),
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  checkpoint_id INTEGER,
  created_by INTEGER,
  verified_by INTEGER,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  closed_at TIMESTAMP,
  CONSTRAINT fk_incidents_checkpoint
    FOREIGN KEY (checkpoint_id)
    REFERENCES checkpoints(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_incidents_created_by
    FOREIGN KEY (created_by)
    REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_incidents_verified_by
    FOREIGN KEY (verified_by)
    REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

-- Alerts
CREATE TABLE IF NOT EXISTS alerts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id INTEGER NOT NULL,
  category VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_alerts_incident
    FOREIGN KEY (incident_id)
    REFERENCES incidents(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- Alert subscriptions
CREATE TABLE IF NOT EXISTS alert_subscriptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  radius_km INTEGER,
  category VARCHAR(50),
  created_at TIMESTAMP,
  CONSTRAINT fk_alert_subscriptions_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- Checkpoint status history
CREATE TABLE IF NOT EXISTS checkpoint_status_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  checkpoint_id INTEGER,
  status VARCHAR(50),
  changed_at TIMESTAMP,
  changed_by INTEGER,
  CONSTRAINT fk_checkpoint_status_checkpoint
    FOREIGN KEY (checkpoint_id)
    REFERENCES checkpoints(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_checkpoint_status_changed_by
    FOREIGN KEY (changed_by)
    REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

-- External API cache
CREATE TABLE IF NOT EXISTS external_api_cache (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_name VARCHAR(100),
  request_hash TEXT,
  response_data JSONB,
  expires_at TIMESTAMP,
  created_at TIMESTAMP
);

-- Report votes
CREATE TABLE IF NOT EXISTS report_votes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id INTEGER,
  user_id INTEGER,
  vote VARCHAR(10),
  created_at TIMESTAMP,
  CONSTRAINT fk_report_votes_report
    FOREIGN KEY (report_id)
    REFERENCES reports(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_report_votes_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- Report comments
CREATE TABLE IF NOT EXISTS report_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id INTEGER,
  user_id INTEGER,
  comment TEXT,
  created_at TIMESTAMP,
  CONSTRAINT fk_report_comments_report
    FOREIGN KEY (report_id)
    REFERENCES reports(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_report_comments_user
    FOREIGN KEY (user_id)
    REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

-- Moderation logs
CREATE TABLE IF NOT EXISTS moderation_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(20),
  event_id INTEGER,
  performed_by INTEGER,
  action VARCHAR(50),
  reason TEXT,
  created_at TIMESTAMP,
  CONSTRAINT fk_moderation_logs_user
    FOREIGN KEY (performed_by)
    REFERENCES users(id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS idx_reports_user_id ON reports(user_id);
CREATE INDEX IF NOT EXISTS idx_reports_duplicate_of ON reports(duplicate_of);
CREATE INDEX IF NOT EXISTS idx_incidents_checkpoint_id ON incidents(checkpoint_id);
CREATE INDEX IF NOT EXISTS idx_incidents_created_by ON incidents(created_by);
CREATE INDEX IF NOT EXISTS idx_incidents_verified_by ON incidents(verified_by);
CREATE INDEX IF NOT EXISTS idx_alerts_incident_id ON alerts(incident_id);
CREATE INDEX IF NOT EXISTS idx_alert_subscriptions_user_id ON alert_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_checkpoint_status_history_checkpoint_id ON checkpoint_status_history(checkpoint_id);
CREATE INDEX IF NOT EXISTS idx_checkpoint_status_history_changed_by ON checkpoint_status_history(changed_by);
CREATE INDEX IF NOT EXISTS idx_report_votes_report_id ON report_votes(report_id);
CREATE INDEX IF NOT EXISTS idx_report_votes_user_id ON report_votes(user_id);
CREATE INDEX IF NOT EXISTS idx_report_comments_report_id ON report_comments(report_id);
CREATE INDEX IF NOT EXISTS idx_report_comments_user_id ON report_comments(user_id);
CREATE INDEX IF NOT EXISTS idx_moderation_logs_performed_by ON moderation_logs(performed_by);

COMMIT;
